export enum actionTypes {
   ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART",
   DECREASE_COUNT_IN_CART = "DECREASE_COUNT_IN_CART",
   REMOVE_FROM_CART = "REMOVE_FROM_CART",
   COMPLETE_CHECKOUT = "COMPLETE_CHECKOUT",
}